### ISSUE TITLE
void return

### ISSUE THREAD

**Issue by MeisterGitarrenheld** [freddie-freeloader/Tiny-Java#20]
The Parser throws an exception for the following program:
```java
class VRet{void MyVoid(){return;}}
```
It probably can not handle `return;`

**Comment by freddie-freeloader** [comment]
This input let us hit the to existing `undefine` in 
https://github.com/freddie-freeloader/Tiny-Java/blob/084c11ac954cc7d81cfb39aaaa364d42370add7d/src/Compiler/Parser.hs#L367
and
https://github.com/freddie-freeloader/Tiny-Java/blob/084c11ac954cc7d81cfb39aaaa364d42370add7d/src/Compiler/Parser.hs#L372
