### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by freddie-freeloader** [freddie-freeloader/Tiny-Java#26]
Hey @Payathp, @MeisterGitarrenheld, @Wh0Els3, @HakanPayat!

Ich sitze gerade mit @fillchen auf dem Sand - genauer im fsi-Zimmer - und wir tragen alles zusammen, was für noch brauchen, um den Compiler lauffähig zu machen.

Dafür wäre der Input von möglichst vielen Leuten wertvoll. 🙂 

Also wäre es cool, wenn ihr (falls Zeit ist) dazu kommt oder hier, in diesem Issue, alle offenen Aufgaben sammelt und diskutiert.

Happy hacking! 🎉

**Comment by freddie-freeloader** [comment]
# Notwendige Bedingungen für lauffähigen Compiler

- [ ] Parser exports one function with the signature `String -> Either Error Ast`)
- [ ] Typechecker exports one function with signature `Ast -> Either Error Ast`
- [ ] Bytecodegenerator exports one function,
      which accepts an AST and produces Bytecode of some type, that can be written into a file
- [ ] One main module that uses all the functions above and adds the functionality to:
      - [ ] Read from a file java code
      - [ ] Write to a file java bytecode
      - [ ] Report error, if the compilation fails

**Comment by MeisterGitarrenheld** [comment]
Hey, ich schreibe gleich noch eine Klausur, aber wenn ihr nachher (so 17:30 - 18:00 Uhr) noch auf dem Sand seid könnte ich kurz vorbeikommen.
Ansonsten könnte ich mich heut Abend dran machen ein Skript zu erstellen, was ein Java File liest und dann eure Funktionen aufruft und das Ergebnis dann in ein File schreibt.
Ich weiß allerdings nicht ob ich auf irgendwas bestimmtes achten muss wegen dem Stack.

**Comment by freddie-freeloader** [comment]
> Ansonsten könnte ich mich heut Abend dran machen ein Skript zu erstellen, was ein Java File liest und dann eure Funktionen aufruft und das Ergebnis dann in ein File schreibt.

Daran werde ich mich gleich setzen 🙂 

Wir haben jetzt ausgemacht, dass wir uns morgen ca. 12 Uhr auf dem Sand treffen und dann noch einen Last-Minute-Hackathon.

**Comment by MeisterGitarrenheld** [comment]
In Ordnung, dann komm ich morgen um 14 Uhr auch vorbei.
